variables:
  imageName: 'macOS-latest'
  nodeVersion: '12.x'

pool:
  vmImage: '$(imageName)'

steps:
  - task: 'UseNode@1'
    displayName: 'Install Node.js v$(nodeVersion)'
    inputs:
      version: '$(nodeVersion)'
      checkLatest: true
  - script: |
      node --print "'node v' + process.versions.node"
      node --print "'npm  v' + child_process.execSync('npm --version')"
    displayName: 'Log Node.js/npm versions'
  - script: |
      git fetch origin build-fix-build-on-mac
      git reset --hard FETCH_HEAD~1
    displayName: 'Fetch branch'
  - script: |
      npm install --global yarn
      yarn install
    displayName: 'Install dependencies'
  - script: './scripts/build-packages-dist.sh'
    displayName: 'Build'
